apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: klipper-claim
  name: klipper-claim
spec:
  storageClassName: klipper-manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: moonraker-claim
  name: moonraker-claim
spec:
  storageClassName: moonraker-manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: gcode-claim
  name: gcode-claim
spec:
  storageClassName: gcode-manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---