apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume-klipper
  labels:
    type: local
spec:
  storageClassName: klipper-manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/klipper"
  persistentVolumeReclaimPolicy: Retain
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - peuleu-worker1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume-moonraker
  labels:
    type: local
spec:
  storageClassName: moonraker-manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/moonraker"
  persistentVolumeReclaimPolicy: Retain
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - peuleu-worker1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume-gcode
  labels:
    type: local
spec:
  storageClassName: gcode-manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/gcode"
  persistentVolumeReclaimPolicy: Retain
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - peuleu-worker1
---
