apiVersion: v1
kind: Service
metadata:
  name: triproxy
  namespace: stf
spec:
  type: ClusterIP
  ports:
  - name: pub
    port: 7150
    targetPort: 7150
    protocol: TCP
  - name: dealer
    port: 7160
    targetPort: 7160
    protocol: TCP
  - name: pull
    port: 7170
    targetPort: 7170
    protocol: TCP
  selector:
    app: triproxy
