apiVersion: v1
kind: Service
metadata:
  name: websocket
  namespace: stf
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: stf-websocket
