apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rethinkdb-data
  namespace: stf
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path  # Ajuster selon votre storageClass
