apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: klipper
  name: klipper
spec:

  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: klipper
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/klipper-web-control-docker-default: "true"
        io.kompose.service: klipper
    spec:
      initContainers:
        - name: init-copy-config
          image: alphaldz/klipper_moonraker:latest
          command: ["/bin/sh", "-c"]
          args: [
            "FOLDERS=\".bash_logout .bashrc .cache gcode_files .klipper_repo_backup klippy-env moonraker moonraker-env .profile .config klipper klipper_z_calibration .moonraker .moonraker_database .moonraker_repo_backup\"; \
            for FOLDER in $FOLDERS; do \
              if [ ! -d /mnt/config/$FOLDER ]; then \
                cp -r /home/klippy/$FOLDER /mnt/config/; \
              fi; \
            done"
          ]

          volumeMounts:
            - mountPath: /mnt/config/
              name: klipper-claim
      containers:
        - image: alphaldz/klipper_moonraker:latest
          name: klipper
          ports:
            - containerPort: 7125
              hostPort: 7125
              protocol: TCP
          securityContext:
            capabilities:
              add:
                - SYS_NICE
            privileged: true

          volumeMounts:
            - mountPath: /home/klippy/
              name: klipper-claim
            - name: usb-device
              mountPath: /dev/ttyUSB0
      nodeName: peuleu-worker1
      restartPolicy: Always
      volumes:
        - name: klipper-claim
          persistentVolumeClaim:
            claimName: klipper-claim
        - name: usb-device
          hostPath:
            path: /dev/ttyUSB0
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: klipper
  name: klipper
spec:
  ports:
    - name: "7125"
      port: 7125
      targetPort: 7125
  selector:
    io.kompose.service: klipper
