apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: klipper
  name: klipper
spec:

  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: klipper
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/klipper-web-control-docker-default: "true"
        io.kompose.service: klipper
    spec:
      initContainers:
        - name: init-copy-config
          image: alphaldz/klipper_moonraker:latest
          command: ["/bin/sh", "-c", "if [ -z \"$(ls -A /mnt/config)\" ]; then cp -r /home/klippy/.config/* /mnt/config/; fi"]
          volumeMounts:
            - mountPath: /mnt/config/
              name: klipper-claim1
      containers:
        - image: alphaldz/klipper_moonraker:latest
          name: klipper
          ports:
            - containerPort: 7125
              hostPort: 7125
              protocol: TCP
          securityContext:
            capabilities:
              add:
                - SYS_NICE
            privileged: true

          volumeMounts:
            - mountPath: /home/klippy/gcode_files
              name: gcode-files
            - mountPath: /home/klippy/.config
              name: klipper-claim1
            - mountPath: /home/klippy/.moonraker_database
              name: moonraker-data
            - name: usb-device
              mountPath: /dev/ttyUSB0
      nodeName: peuleu-worker1
      restartPolicy: Always
      volumes:
        - name: gcode-files
          persistentVolumeClaim:
            claimName: gcode-files
        - name: klipper-claim1
          persistentVolumeClaim:
            claimName: klipper-claim1
        - name: moonraker-data
          persistentVolumeClaim:
            claimName: moonraker-data
        - name: usb-device
          hostPath:
            path: /dev/ttyUSB0
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: klipper
  name: klipper
spec:
  ports:
    - name: "7125"
      port: 7125
      targetPort: 7125
  selector:
    io.kompose.service: klipper
