apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: klipper
  name: klipper
spec:

  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: klipper
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/klipper-web-control-docker-default: "true"
        io.kompose.service: klipper
    spec:
      initContainers:
        - name: init-copy-config
          image: 'alphaldz/klipper_moonraker:latest'
          imagePullPolicy: Always

          command: ['sh', '-c', '/home/klippy/init-copy-config.sh']

          volumeMounts:
            - mountPath: /mnt/config/
              name: klipper-claim
      containers:
        - name: klipper
          image: 'alphaldz/klipper_moonraker:latest'
          imagePullPolicy: Always

          ports:
            - containerPort: 7125
              hostPort: 7125
              protocol: TCP

          securityContext:
            capabilities:
              add:
                - SYS_NICE
            privileged: true

          volumeMounts:
            - mountPath: /home/klippy/
              name: klipper-claim
            - name: usb-device
              mountPath: /dev/ttyUSB0

      nodeName: peuleu-worker1
      restartPolicy: Always
      volumes:
        - name: klipper-claim
          persistentVolumeClaim:
            claimName: klipper-claim
        - name: usb-device
          hostPath:
            path: /dev/ttyUSB0
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: klipper
  name: klipper
spec:
  ports:
    - name: "7125"
      port: 7125
      targetPort: 7125
  selector:
    io.kompose.service: klipper
