apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: mainsail
  name: mainsail
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mainsail
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/klipper-web-control-docker-default: "true"
        io.kompose.service: mainsail
    spec:
      containers:
        - image: dimalo/mainsail
          name: mainsail
          ports:
            - containerPort: 80
              hostPort: 8011
              protocol: TCP
      nodeName: peuleu-worker1
      restartPolicy: Always
