apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: klipper-claim
  name: klipper-claim
spec:
  storageClassName: manual-klipper
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
