apiVersion: apps/v1
kind: Deployment
metadata:
  name: "fullname"
  namespace: "nextcloud"
  labels:
    app: "nextcloud.name"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: "nextcloud.name"
  template:
    metadata:
      labels:
        app: "nextcloud.name"
    spec:
      containers:
        - name: nextcloud
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
          volumeMounts:
            - name: nextcloud-data
              mountPath: /var/www/html
      volumes:
        - name: nextcloud-data
          persistentVolumeClaim:
            claimName: nextcloud-claim

