


apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-pvc
  labels:
    type: local
spec:
  storageClassName: nextcloud-pvc
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/nextcloud"
  persistentVolumeReclaimPolicy: Retain
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - peuleu-worker1
