apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-claim
  namespace: nextcloud
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: 100Gi
  storageClassName: nextcloud-pvc

