name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        working-directory: ./klipper
        run: docker build --platform linux/amd64 -t alphaldz/klipper_moonraker:latest -f ./klipper/Dockerfile .
      
      - name: Push Docker image
        working-directory: ./klipper
        run: docker push --platform linux/amd64 alphaldz/klipper_moonraker:latest
