name: Docker Build and Push

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow on pull request to the main branch

jobs:
  build-and-push:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Ensure Docker is using Linux containers
        run: |
          docker info --format '{{.OSType}}' | findstr /C:"linux" >nul || echo "Docker must be switched to Linux containers manually."
        shell: cmd

      - name: Log in to Docker Hub
        run: |
          echo %DOCKER_PASSWORD% | docker login --username %DOCKER_USERNAME% --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        shell: cmd

      - name: Build and push Docker image
        working-directory: ./klipper
        run: |
          docker build . -t alphaldz/klipper_moonraker:latest -f ./klipper/Dockerfile
          docker push alphaldz/klipper_moonraker:latest
        shell: cmd
