apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: postgres
type: Opaque
stringData:
  # Generate with: openssl rand -hex 20
  POSTGRES_PASSWORD: "127fc2077c44dd19b993db773f9d7fd8c17e1545"
